2019-04-08 19:03:22,772 - [updatemp.py:109] - ERROR - Exception Logged: updatemp
Traceback (most recent call last):
  File "D:/GitHub/wechat_sogou_crawl/updatemp.py", line 82, in <module>
    index_html_path = wechats.down_html(wz_item['content_url'], wz_item['title'])
  File "D:\GitHub\wechat_sogou_crawl\wechatsogou\api.py", line 262, in down_html
    ct = re.findall('var ct = "(.*?)";', content)[0]
IndexError: list index out of range
2019-04-08 19:23:26,863 - [updatemp.py:109] - ERROR - Exception Logged: updatemp
Traceback (most recent call last):
  File "D:/GitHub/wechat_sogou_crawl/updatemp.py", line 82, in <module>
    index_html_path = wechats.down_html(wz_item['content_url'], wz_item['title'])
  File "D:\GitHub\wechat_sogou_crawl\wechatsogou\api.py", line 262, in down_html
    ct = re.findall('var ct = "(.*?)";', content)[0]
IndexError: list index out of range
